# platform :ios, '9.0'
# Uncomment the next line to define a global platform for your project

target 'MIST' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MIST
  pod 'Firebase'
  pod 'Firebase/Auth'
  pod 'Firebase/Messaging'
  pod 'Firebase/Database'
  target 'MISTTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MISTUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
